kind = "DojoModel"
class_hash = "0x549c99ed44037b3e7937e18c18cfe66558f0e4fd21afc8dbdf13734205ecb78"
original_class_hash = "0x549c99ed44037b3e7937e18c18cfe66558f0e4fd21afc8dbdf13734205ecb78"
abi = "manifests/dev/abis/base/models/matchmaker_models_player_player.json"
name = "matchmaker::models::player::player"

[[members]]
name = "registry_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "league_id"
type = "u8"
key = false

[[members]]
name = "index"
type = "u32"
key = false

[[members]]
name = "rating"
type = "u32"
key = false
