kind = "DojoModel"
class_hash = "0x123699e6ea4e6f6b8a49e5ead3a787814f258c2333ffec84ed28f9c67bcc989"
original_class_hash = "0x123699e6ea4e6f6b8a49e5ead3a787814f258c2333ffec84ed28f9c67bcc989"
abi = "manifests/dev/abis/base/models/matchmaker_models_player_player.json"
name = "matchmaker::models::player::player"

[[members]]
name = "registry_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "ContractAddress"
key = true

[[members]]
name = "league_id"
type = "u8"
key = false

[[members]]
name = "index"
type = "u32"
key = false

[[members]]
name = "rating"
type = "u32"
key = false
