[package]
name = "matchmaker"
version = "0.0.0"
description = "Example of elo rating crate usage."
homepage = "https://github.com/dojoengine/origami/tree/examples/matchmaker"

[scripts]
deploy = "sozo build && sozo migrate plan && sozo migrate apply && ./scripts/katana.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }
origami = { git = "https://github.com/Bal7hazar/origami.git", rev = "4e92356" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
# Local
rpc_url = "http://localhost:5050/"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
# Slot
# rpc_url = "https://api.cartridge.gg/x/matchmaker/katana"
# account_address = "0x5eeb6320498caa764110c1f0f385dfd3d679b7d32438a804d399351a06c78d9"
# private_key = "0x566bf241908d6bf95d686469f8659825e5ae6b4a8a74313ed6f1d61b09ed64b"