[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x15cc43807e3cdf2b518aefc7328ed8f1b3490442603b02b519c8749e14b23ab"
transaction_hash = "0x62f5de5acf9675dd33e0b848514e7a3717a625d04efb7926454a6538a29bde6"
block_number = 3
seed = "matchmaker"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x160a189a9d2e358f59a523903a1986fed686a3ca39e040ed84e68c0b017762a"
class_hash = "0x180fbcb6342efec0588a1857fed8723091c31fd5da2b4ce6f0daecf46476848"
original_class_hash = "0x180fbcb6342efec0588a1857fed8723091c31fd5da2b4ce6f0daecf46476848"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/matchmaker_systems_maker_maker.json"
reads = []
writes = []
computed = []
name = "matchmaker::systems::maker::maker"

[[models]]
kind = "DojoModel"
class_hash = "0x222115e8b4b6e558ba985275cfc93ea391058d3dab521c846abf0b0e9942115"
original_class_hash = "0x222115e8b4b6e558ba985275cfc93ea391058d3dab521c846abf0b0e9942115"
abi = "abis/deployments/models/matchmaker_models_league_league.json"
name = "matchmaker::models::league::league"

[[models.members]]
name = "registry_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "size"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x549c99ed44037b3e7937e18c18cfe66558f0e4fd21afc8dbdf13734205ecb78"
original_class_hash = "0x549c99ed44037b3e7937e18c18cfe66558f0e4fd21afc8dbdf13734205ecb78"
abi = "abis/deployments/models/matchmaker_models_player_player.json"
name = "matchmaker::models::player::player"

[[models.members]]
name = "registry_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "league_id"
type = "u8"
key = false

[[models.members]]
name = "index"
type = "u32"
key = false

[[models.members]]
name = "rating"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4bebec14c64f4c511ffce4d1962a0507b222895a9cb00f4616736f3b2a46d7c"
original_class_hash = "0x4bebec14c64f4c511ffce4d1962a0507b222895a9cb00f4616736f3b2a46d7c"
abi = "abis/deployments/models/matchmaker_models_registry_registry.json"
name = "matchmaker::models::registry::registry"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "leagues"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x44e1f9d46a3d0a95b434aca4d673fd91db582867296e888588c64e5a448b434"
original_class_hash = "0x44e1f9d46a3d0a95b434aca4d673fd91db582867296e888588c64e5a448b434"
abi = "abis/deployments/models/matchmaker_models_slot_slot.json"
name = "matchmaker::models::slot::slot"

[[models.members]]
name = "registry_id"
type = "u32"
key = true

[[models.members]]
name = "league_id"
type = "u8"
key = true

[[models.members]]
name = "index"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = false
